/**
 * Collects data-goke-styles + data-goke-hover from the live DOM and
 * emits real CSS (including @media) so tablet/mobile edits survive publish.
 */

import type { Breakpoint, CSSProps, ResponsiveStyles } from "../types/document";

const STYLE_ATTR = "data-goke-styles";
const HOVER_ATTR = "data-goke-hover";
const ID_ATTR = "data-goke-id";
const STYLE_TAG_ID = "goke-editor-responsive";

const BREAKPOINTS: { id: Breakpoint; maxWidth?: number }[] = [
  { id: "desktop" },
  { id: "tablet", maxWidth: 1024 },
  { id: "mobile", maxWidth: 640 },
];

function ensureStableId(el: HTMLElement, index: number): string {
  let id = el.getAttribute(ID_ATTR) || el.id;
  if (!id) {
    id = `goke_n_${index}_${Math.random().toString(36).slice(2, 7)}`;
    el.setAttribute(ID_ATTR, id);
  }
  if (!el.id && id.startsWith("goke_")) {
    // Prefer attribute selector; id optional
  }
  return id;
}

function parseJson<T>(raw: string | null): T | null {
  if (!raw) return null;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

function propsToCss(props: CSSProps): string {
  return Object.entries(props)
    .filter(([, v]) => v != null && String(v).trim() !== "")
    .map(([k, v]) => `  ${k}: ${v} !important;`)
    .join("\n");
}

function selectorFor(id: string): string {
  // Prefer data-goke-id (always set by editor); fall back to #id
  return `[data-goke-id="${id}"]`;
}

/**
 * Build a full CSS stylesheet from editor annotations on the document.
 */
export function buildResponsiveCss(doc: Document): string {
  const all = Array.from(doc.querySelectorAll<HTMLElement>("*"));
  const blocks: {
    id: string;
    styles: ResponsiveStyles;
    hover?: CSSProps;
  }[] = [];

  let i = 0;
  for (const el of all) {
    const styles = parseJson<ResponsiveStyles>(el.getAttribute(STYLE_ATTR));
    const hover = parseJson<CSSProps>(el.getAttribute(HOVER_ATTR));
    if (!styles && !hover) continue;
    const id = ensureStableId(el, i++);
    blocks.push({ id, styles: styles || {}, hover: hover || undefined });
  }

  if (blocks.length === 0) return "";

  const parts: string[] = [];
  parts.push("/* Generated by Goke editor — responsive + hover */");

  // Desktop (base)
  for (const b of blocks) {
    const desktop = b.styles.desktop;
    if (desktop && Object.keys(desktop).length) {
      parts.push(`${selectorFor(b.id)} {\n${propsToCss(desktop)}\n}`);
    }
    if (b.hover && Object.keys(b.hover).length) {
      parts.push(`${selectorFor(b.id)}:hover {\n${propsToCss(b.hover)}\n}`);
    }
  }

  // Tablet
  const tabletRules: string[] = [];
  for (const b of blocks) {
    const t = b.styles.tablet;
    if (t && Object.keys(t).length) {
      tabletRules.push(`${selectorFor(b.id)} {\n${propsToCss(t)}\n}`);
    }
  }
  if (tabletRules.length) {
    parts.push(`@media (max-width: 1024px) {\n${tabletRules.join("\n")}\n}`);
  }

  // Mobile
  const mobileRules: string[] = [];
  for (const b of blocks) {
    const m = b.styles.mobile;
    if (m && Object.keys(m).length) {
      mobileRules.push(`${selectorFor(b.id)} {\n${propsToCss(m)}\n}`);
    }
  }
  if (mobileRules.length) {
    parts.push(`@media (max-width: 640px) {\n${mobileRules.join("\n")}\n}`);
  }

  return parts.join("\n\n");
}

/**
 * Inject or replace <style id="goke-editor-responsive"> in the document
 * so tablet/mobile/hover survive serialization and deploy.
 */
export function applyResponsiveStylesToDocument(doc: Document): void {
  const css = buildResponsiveCss(doc);
  let tag = doc.getElementById(STYLE_TAG_ID) as HTMLStyleElement | null;
  if (!css) {
    tag?.remove();
    return;
  }
  if (!tag) {
    tag = doc.createElement("style");
    tag.id = STYLE_TAG_ID;
    doc.head?.appendChild(tag);
  }
  tag.textContent = css;
}

/**
 * Apply the active breakpoint's stored styles as live inline styles
 * so the canvas matches Desktop/Tablet/Mobile while editing.
 */
export function applyBreakpointPreview(
  doc: Document,
  breakpoint: Breakpoint
): void {
  const all = Array.from(doc.querySelectorAll<HTMLElement>(`[${STYLE_ATTR}]`));
  for (const el of all) {
    const store = parseJson<ResponsiveStyles>(el.getAttribute(STYLE_ATTR));
    if (!store) continue;

    // Clear previous preview props we might have set — re-apply cascade:
    // desktop base, then tablet/mobile override for preview
    const cascade: CSSProps = {
      ...(store.desktop || {}),
      ...(breakpoint === "tablet" || breakpoint === "mobile"
        ? store.tablet || {}
        : {}),
      ...(breakpoint === "mobile" ? store.mobile || {} : {}),
    };

    for (const [prop, val] of Object.entries(cascade)) {
      el.style.setProperty(prop, val);
    }
  }
}

export { STYLE_ATTR, HOVER_ATTR, ID_ATTR, STYLE_TAG_ID, BREAKPOINTS };
